import React from "react";
import aboutImage from "public/aboutimg.jpg";
import Image from "next/image";
import Head from "next/head";
import Subscribe from "@/components/Subscribe";
const about = () => {
  return (
    <>
      <Head>
        <title>BEDROK | About Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="">
        <div className="container px-5 lg:px-0 sm:mt-[72px] mt-8 mb-36 sm:mb-24">
          <div id="hero" className="">
            <div className="relative sm:h-96 sm:p-89 h-full w-auto rounded-my">
              <Image
                src={aboutImage}
                alt="bg"
                className="h-full object-cover rounded-my"
              />
              <div className="absolute mt-6 sm:mt-0 pb-6 sm:bottom-5 sm:left-5 ">
                <p className="uppercase font-semibold text-xl tracking-widest text-[#C7C9D1]">
                  ABOUT ME
                </p>
                <p className="sm:text-lg text-[40px] font-normal sm:font-light md:text-7xl text-black sm:text-white">
                  Hey, I’m Isaiah
                </p>
              </div>
            </div>
          </div>
        </div>
        <div className="border-t-[1px]">
          <div className="container px-5 lg:px-0 flex flex-col sm:flex-row gap-6 sm:mt-[74px] mt-14 mb-24 sm:mb-28 ">
            <div className="md:w-4/12 w-full">
              <h1 className="text-black text-3xl">My Story</h1>
            </div>
            <div className="md:w-4/12 w-full">
              <p className="text-[#454854] text-[16px]">
                Eum fuga reprehenderit tempore quidem suscipit fugiat a
                recusandae minima. Debitis et exercitationem. Nisi vero
                deserunt. Expedita aut fugiat autem similique officiis. Qui quo
                repellendus voluptatum. Quia nemo voluptatem cumque aut
                blanditiis neque.
              </p>
            </div>
            <div className="md:w-4/12 w-full">
              <p className="text-[#454854] text-[16px]">
                Eum fuga reprehenderit tempore quidem suscipit fugiat a
                recusandae minima. Debitis et exercitationem. Nisi vero
                deserunt. Expedita aut fugiat autem similique officiis. Qui quo
                repellendus voluptatum. Quia nemo voluptatem cumque aut
                blanditiis neque.
              </p>
            </div>
          </div>
        </div>
      </div>
      <Subscribe />
    </>
  );
};

export default about;
