import Head from "next/head";
import { Inter } from "@next/font/google";
import { GraphQLClient, gql } from "graphql-request";
import FeaturedPost from "@/components/FeaturedPost";
import { getFeaturedPost, getPosts, getRecentPosts } from "lib/graphcms";
import RecentPosts from "@/components/RecentPosts";
import Subscribe from "@/components/Subscribe";
const inter = Inter({
  subsets: ["latin"],
  variable: "--display-font",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

export async function getStaticProps() {
  const posts = (await getPosts()) || [];
  const featuredPost = (await getFeaturedPost()) || [];
  const recentPosts = (await getRecentPosts()) || [];
  return {
    props: { posts, recentPosts, featuredPost, recentPosts },
  };
}

export default function Home({ posts, recentPosts, featuredPost }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="font-display">
        <div className="px-5 lg:px-0 md:container ">
          <FeaturedPost data={featuredPost} />

          <RecentPosts data={recentPosts} />
        </div>
        <Subscribe />
      </div>
    </>
  );
}
